//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWPFServiceAuto.RefService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Masina", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Masina : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumarInmatriculareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProblemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumarInmatriculare {
            get {
                return this.NumarInmatriculareField;
            }
            set {
                if ((object.ReferenceEquals(this.NumarInmatriculareField, value) != true)) {
                    this.NumarInmatriculareField = value;
                    this.RaisePropertyChanged("NumarInmatriculare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Problema {
            get {
                return this.ProblemaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProblemaField, value) != true)) {
                    this.ProblemaField = value;
                    this.RaisePropertyChanged("Problema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name numar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugaMasina", ReplyAction="*")]
        ClientWPFServiceAuto.RefService.AdaugaMasinaResponse AdaugaMasina(ClientWPFServiceAuto.RefService.AdaugaMasinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugaMasina", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.AdaugaMasinaResponse> AdaugaMasinaAsync(ClientWPFServiceAuto.RefService.AdaugaMasinaRequest request);
        
        // CODEGEN: Generating message contract since element name ObtineMasiniResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtineMasini", ReplyAction="*")]
        ClientWPFServiceAuto.RefService.ObtineMasiniResponse ObtineMasini(ClientWPFServiceAuto.RefService.ObtineMasiniRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtineMasini", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.ObtineMasiniResponse> ObtineMasiniAsync(ClientWPFServiceAuto.RefService.ObtineMasiniRequest request);
        
        // CODEGEN: Generating message contract since element name StergeMasinaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergeMasina", ReplyAction="*")]
        ClientWPFServiceAuto.RefService.StergeMasinaResponse StergeMasina(ClientWPFServiceAuto.RefService.StergeMasinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergeMasina", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.StergeMasinaResponse> StergeMasinaAsync(ClientWPFServiceAuto.RefService.StergeMasinaRequest request);
        
        // CODEGEN: Generating message contract since element name numar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaMasina", ReplyAction="*")]
        ClientWPFServiceAuto.RefService.ModificaMasinaResponse ModificaMasina(ClientWPFServiceAuto.RefService.ModificaMasinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaMasina", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.ModificaMasinaResponse> ModificaMasinaAsync(ClientWPFServiceAuto.RefService.ModificaMasinaRequest request);
        
        // CODEGEN: Generating message contract since element name numarCautat from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautaMasina", ReplyAction="*")]
        ClientWPFServiceAuto.RefService.CautaMasinaResponse CautaMasina(ClientWPFServiceAuto.RefService.CautaMasinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautaMasina", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.CautaMasinaResponse> CautaMasinaAsync(ClientWPFServiceAuto.RefService.CautaMasinaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugaMasinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugaMasina", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.AdaugaMasinaRequestBody Body;
        
        public AdaugaMasinaRequest() {
        }
        
        public AdaugaMasinaRequest(ClientWPFServiceAuto.RefService.AdaugaMasinaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugaMasinaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string problema;
        
        public AdaugaMasinaRequestBody() {
        }
        
        public AdaugaMasinaRequestBody(string numar, string marca, string problema) {
            this.numar = numar;
            this.marca = marca;
            this.problema = problema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugaMasinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugaMasinaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.AdaugaMasinaResponseBody Body;
        
        public AdaugaMasinaResponse() {
        }
        
        public AdaugaMasinaResponse(ClientWPFServiceAuto.RefService.AdaugaMasinaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugaMasinaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdaugaMasinaResult;
        
        public AdaugaMasinaResponseBody() {
        }
        
        public AdaugaMasinaResponseBody(string AdaugaMasinaResult) {
            this.AdaugaMasinaResult = AdaugaMasinaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtineMasiniRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtineMasini", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.ObtineMasiniRequestBody Body;
        
        public ObtineMasiniRequest() {
        }
        
        public ObtineMasiniRequest(ClientWPFServiceAuto.RefService.ObtineMasiniRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtineMasiniRequestBody {
        
        public ObtineMasiniRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtineMasiniResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtineMasiniResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.ObtineMasiniResponseBody Body;
        
        public ObtineMasiniResponse() {
        }
        
        public ObtineMasiniResponse(ClientWPFServiceAuto.RefService.ObtineMasiniResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtineMasiniResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWPFServiceAuto.RefService.Masina[] ObtineMasiniResult;
        
        public ObtineMasiniResponseBody() {
        }
        
        public ObtineMasiniResponseBody(ClientWPFServiceAuto.RefService.Masina[] ObtineMasiniResult) {
            this.ObtineMasiniResult = ObtineMasiniResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StergeMasinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StergeMasina", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.StergeMasinaRequestBody Body;
        
        public StergeMasinaRequest() {
        }
        
        public StergeMasinaRequest(ClientWPFServiceAuto.RefService.StergeMasinaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StergeMasinaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public StergeMasinaRequestBody() {
        }
        
        public StergeMasinaRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StergeMasinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StergeMasinaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.StergeMasinaResponseBody Body;
        
        public StergeMasinaResponse() {
        }
        
        public StergeMasinaResponse(ClientWPFServiceAuto.RefService.StergeMasinaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StergeMasinaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StergeMasinaResult;
        
        public StergeMasinaResponseBody() {
        }
        
        public StergeMasinaResponseBody(string StergeMasinaResult) {
            this.StergeMasinaResult = StergeMasinaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaMasinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaMasina", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.ModificaMasinaRequestBody Body;
        
        public ModificaMasinaRequest() {
        }
        
        public ModificaMasinaRequest(ClientWPFServiceAuto.RefService.ModificaMasinaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaMasinaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string problema;
        
        public ModificaMasinaRequestBody() {
        }
        
        public ModificaMasinaRequestBody(int id, string numar, string marca, string problema) {
            this.id = id;
            this.numar = numar;
            this.marca = marca;
            this.problema = problema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaMasinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaMasinaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.ModificaMasinaResponseBody Body;
        
        public ModificaMasinaResponse() {
        }
        
        public ModificaMasinaResponse(ClientWPFServiceAuto.RefService.ModificaMasinaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaMasinaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificaMasinaResult;
        
        public ModificaMasinaResponseBody() {
        }
        
        public ModificaMasinaResponseBody(string ModificaMasinaResult) {
            this.ModificaMasinaResult = ModificaMasinaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautaMasinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautaMasina", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.CautaMasinaRequestBody Body;
        
        public CautaMasinaRequest() {
        }
        
        public CautaMasinaRequest(ClientWPFServiceAuto.RefService.CautaMasinaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautaMasinaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numarCautat;
        
        public CautaMasinaRequestBody() {
        }
        
        public CautaMasinaRequestBody(string numarCautat) {
            this.numarCautat = numarCautat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautaMasinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautaMasinaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWPFServiceAuto.RefService.CautaMasinaResponseBody Body;
        
        public CautaMasinaResponse() {
        }
        
        public CautaMasinaResponse(ClientWPFServiceAuto.RefService.CautaMasinaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautaMasinaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWPFServiceAuto.RefService.Masina[] CautaMasinaResult;
        
        public CautaMasinaResponseBody() {
        }
        
        public CautaMasinaResponseBody(ClientWPFServiceAuto.RefService.Masina[] CautaMasinaResult) {
            this.CautaMasinaResult = CautaMasinaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientWPFServiceAuto.RefService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientWPFServiceAuto.RefService.WebService1Soap>, ClientWPFServiceAuto.RefService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPFServiceAuto.RefService.AdaugaMasinaResponse ClientWPFServiceAuto.RefService.WebService1Soap.AdaugaMasina(ClientWPFServiceAuto.RefService.AdaugaMasinaRequest request) {
            return base.Channel.AdaugaMasina(request);
        }
        
        public string AdaugaMasina(string numar, string marca, string problema) {
            ClientWPFServiceAuto.RefService.AdaugaMasinaRequest inValue = new ClientWPFServiceAuto.RefService.AdaugaMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.AdaugaMasinaRequestBody();
            inValue.Body.numar = numar;
            inValue.Body.marca = marca;
            inValue.Body.problema = problema;
            ClientWPFServiceAuto.RefService.AdaugaMasinaResponse retVal = ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).AdaugaMasina(inValue);
            return retVal.Body.AdaugaMasinaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.AdaugaMasinaResponse> ClientWPFServiceAuto.RefService.WebService1Soap.AdaugaMasinaAsync(ClientWPFServiceAuto.RefService.AdaugaMasinaRequest request) {
            return base.Channel.AdaugaMasinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.AdaugaMasinaResponse> AdaugaMasinaAsync(string numar, string marca, string problema) {
            ClientWPFServiceAuto.RefService.AdaugaMasinaRequest inValue = new ClientWPFServiceAuto.RefService.AdaugaMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.AdaugaMasinaRequestBody();
            inValue.Body.numar = numar;
            inValue.Body.marca = marca;
            inValue.Body.problema = problema;
            return ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).AdaugaMasinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPFServiceAuto.RefService.ObtineMasiniResponse ClientWPFServiceAuto.RefService.WebService1Soap.ObtineMasini(ClientWPFServiceAuto.RefService.ObtineMasiniRequest request) {
            return base.Channel.ObtineMasini(request);
        }
        
        public ClientWPFServiceAuto.RefService.Masina[] ObtineMasini() {
            ClientWPFServiceAuto.RefService.ObtineMasiniRequest inValue = new ClientWPFServiceAuto.RefService.ObtineMasiniRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.ObtineMasiniRequestBody();
            ClientWPFServiceAuto.RefService.ObtineMasiniResponse retVal = ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).ObtineMasini(inValue);
            return retVal.Body.ObtineMasiniResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.ObtineMasiniResponse> ClientWPFServiceAuto.RefService.WebService1Soap.ObtineMasiniAsync(ClientWPFServiceAuto.RefService.ObtineMasiniRequest request) {
            return base.Channel.ObtineMasiniAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.ObtineMasiniResponse> ObtineMasiniAsync() {
            ClientWPFServiceAuto.RefService.ObtineMasiniRequest inValue = new ClientWPFServiceAuto.RefService.ObtineMasiniRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.ObtineMasiniRequestBody();
            return ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).ObtineMasiniAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPFServiceAuto.RefService.StergeMasinaResponse ClientWPFServiceAuto.RefService.WebService1Soap.StergeMasina(ClientWPFServiceAuto.RefService.StergeMasinaRequest request) {
            return base.Channel.StergeMasina(request);
        }
        
        public string StergeMasina(int id) {
            ClientWPFServiceAuto.RefService.StergeMasinaRequest inValue = new ClientWPFServiceAuto.RefService.StergeMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.StergeMasinaRequestBody();
            inValue.Body.id = id;
            ClientWPFServiceAuto.RefService.StergeMasinaResponse retVal = ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).StergeMasina(inValue);
            return retVal.Body.StergeMasinaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.StergeMasinaResponse> ClientWPFServiceAuto.RefService.WebService1Soap.StergeMasinaAsync(ClientWPFServiceAuto.RefService.StergeMasinaRequest request) {
            return base.Channel.StergeMasinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.StergeMasinaResponse> StergeMasinaAsync(int id) {
            ClientWPFServiceAuto.RefService.StergeMasinaRequest inValue = new ClientWPFServiceAuto.RefService.StergeMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.StergeMasinaRequestBody();
            inValue.Body.id = id;
            return ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).StergeMasinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPFServiceAuto.RefService.ModificaMasinaResponse ClientWPFServiceAuto.RefService.WebService1Soap.ModificaMasina(ClientWPFServiceAuto.RefService.ModificaMasinaRequest request) {
            return base.Channel.ModificaMasina(request);
        }
        
        public string ModificaMasina(int id, string numar, string marca, string problema) {
            ClientWPFServiceAuto.RefService.ModificaMasinaRequest inValue = new ClientWPFServiceAuto.RefService.ModificaMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.ModificaMasinaRequestBody();
            inValue.Body.id = id;
            inValue.Body.numar = numar;
            inValue.Body.marca = marca;
            inValue.Body.problema = problema;
            ClientWPFServiceAuto.RefService.ModificaMasinaResponse retVal = ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).ModificaMasina(inValue);
            return retVal.Body.ModificaMasinaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.ModificaMasinaResponse> ClientWPFServiceAuto.RefService.WebService1Soap.ModificaMasinaAsync(ClientWPFServiceAuto.RefService.ModificaMasinaRequest request) {
            return base.Channel.ModificaMasinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.ModificaMasinaResponse> ModificaMasinaAsync(int id, string numar, string marca, string problema) {
            ClientWPFServiceAuto.RefService.ModificaMasinaRequest inValue = new ClientWPFServiceAuto.RefService.ModificaMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.ModificaMasinaRequestBody();
            inValue.Body.id = id;
            inValue.Body.numar = numar;
            inValue.Body.marca = marca;
            inValue.Body.problema = problema;
            return ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).ModificaMasinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPFServiceAuto.RefService.CautaMasinaResponse ClientWPFServiceAuto.RefService.WebService1Soap.CautaMasina(ClientWPFServiceAuto.RefService.CautaMasinaRequest request) {
            return base.Channel.CautaMasina(request);
        }
        
        public ClientWPFServiceAuto.RefService.Masina[] CautaMasina(string numarCautat) {
            ClientWPFServiceAuto.RefService.CautaMasinaRequest inValue = new ClientWPFServiceAuto.RefService.CautaMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.CautaMasinaRequestBody();
            inValue.Body.numarCautat = numarCautat;
            ClientWPFServiceAuto.RefService.CautaMasinaResponse retVal = ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).CautaMasina(inValue);
            return retVal.Body.CautaMasinaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.CautaMasinaResponse> ClientWPFServiceAuto.RefService.WebService1Soap.CautaMasinaAsync(ClientWPFServiceAuto.RefService.CautaMasinaRequest request) {
            return base.Channel.CautaMasinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWPFServiceAuto.RefService.CautaMasinaResponse> CautaMasinaAsync(string numarCautat) {
            ClientWPFServiceAuto.RefService.CautaMasinaRequest inValue = new ClientWPFServiceAuto.RefService.CautaMasinaRequest();
            inValue.Body = new ClientWPFServiceAuto.RefService.CautaMasinaRequestBody();
            inValue.Body.numarCautat = numarCautat;
            return ((ClientWPFServiceAuto.RefService.WebService1Soap)(this)).CautaMasinaAsync(inValue);
        }
    }
}
